package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import java.util.HashSet
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.Id
import javax.persistence.OneToMany
import javax.persistence.Table

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "sdtienda")
class Cliente : java.io.Serializable {
	@get:Id
	@get:Column(name = "vRUC", unique = true, nullable = false, length = 11)
	var vruc: String? = null
	@get:Column(name = "vApellidoPaterno", length = 40)
	var vapellidoPaterno: String? = null
	@get:Column(name = "vApellidoMaterno", length = 40)
	var vapellidoMaterno: String? = null
	@get:Column(name = "vNombre", length = 40)
	var vnombre: String? = null
	@get:Column(name = "vTelefono", length = 7)
	var vtelefono: String? = null
	@get:Column(name = "vCelular", length = 9)
	var vcelular: String? = null
	@get:Column(name = "vDireccion", length = 60)
	var vdireccion: String? = null
	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	var ordencompras: Set<Ordencompra>? = HashSet<Ordencompra>(0)
	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	var usuarios: Set<Usuario>? = HashSet<Usuario>(0)

	constructor() {}
	constructor(vruc: String?) {
		this.vruc = vruc
	}

	constructor(
		vruc: String?, vapellidoPaterno: String?, vapellidoMaterno: String?, vnombre: String?, vtelefono: String?,
		vcelular: String?, vdireccion: String?, ordencompras: Set<Ordencompra>?, usuarios: Set<Usuario>?
	) {
		this.vruc = vruc
		this.vapellidoPaterno = vapellidoPaterno
		this.vapellidoMaterno = vapellidoMaterno
		this.vnombre = vnombre
		this.vtelefono = vtelefono
		this.vcelular = vcelular
		this.vdireccion = vdireccion
		this.ordencompras = ordencompras
		this.usuarios = usuarios
	}
}