package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import java.util.Date
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType.IDENTITY
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table
import javax.persistence.Temporal
import javax.persistence.TemporalType

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", catalog = "sdtienda")
class Factura : java.io.Serializable {
	@get:Id
	@get:GeneratedValue(strategy = IDENTITY)
	@get:Column(name = "vIdFactura", unique = true, nullable = false)
	var vidFactura: Integer? = null
	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "OrdenCompra_vIdOrdenCompra", nullable = false)
	var ordencompra: Ordencompra? = null
	@get:Temporal(TemporalType.DATE)
	@get:Column(name = "dFecha", length = 10)
	var dfecha: Date? = null

	constructor() {}
	constructor(ordencompra: Ordencompra?) {
		this.ordencompra = ordencompra
	}

	constructor(ordencompra: Ordencompra?, dfecha: Date?) {
		this.ordencompra = ordencompra
		this.dfecha = dfecha
	}
}