package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import javax.persistence.AttributeOverride
import javax.persistence.AttributeOverrides
import javax.persistence.Column
import javax.persistence.EmbeddedId
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table

/**
 * OrdencompraHasProducto generated by hbm2java
 */
@Entity
@Table(name = "ordencompra_has_producto", catalog = "sdtienda")
class OrdencompraHasProducto : java.io.Serializable {
	@get:EmbeddedId
	@get:AttributeOverrides(
		AttributeOverride(
			name = "ordenCompraVIdOrdenCompra",
			column = Column(name = "OrdenCompra_vIdOrdenCompra", nullable = false)
		), AttributeOverride(name = "productoVCodigo", column = Column(name = "Producto_vCodigo", nullable = false))
	)
	var id: OrdencompraHasProductoId? = null
	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "Producto_vCodigo", nullable = false, insertable = false, updatable = false)
	var producto: Producto? = null
	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "OrdenCompra_vIdOrdenCompra", nullable = false, insertable = false, updatable = false)
	var ordencompra: Ordencompra? = null
	@get:Column(name = "nCantidad")
	var ncantidad: Integer? = null
	@get:Column(name = "nTotal", precision = 22, scale = 0)
	var ntotal: Double? = null

	constructor() {}
	constructor(id: OrdencompraHasProductoId?, producto: Producto?, ordencompra: Ordencompra?) {
		this.id = id
		this.producto = producto
		this.ordencompra = ordencompra
	}

	constructor(
		id: OrdencompraHasProductoId?, producto: Producto?, ordencompra: Ordencompra?,
		ncantidad: Integer?, ntotal: Double?
	) {
		this.id = id
		this.producto = producto
		this.ordencompra = ordencompra
		this.ncantidad = ncantidad
		this.ntotal = ntotal
	}
}