package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import java.util.Date
import java.util.HashSet
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType.IDENTITY
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.OneToMany
import javax.persistence.Table
import javax.persistence.Temporal
import javax.persistence.TemporalType

/**
 * Ordencompra generated by hbm2java
 */
@Entity
@Table(name = "ordencompra", catalog = "sdtienda")
class Ordencompra : java.io.Serializable {
	@get:Id
	@get:GeneratedValue(strategy = IDENTITY)
	@get:Column(name = "vIdOrdenCompra", unique = true, nullable = false)
	var vidOrdenCompra: Integer? = null
	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "Cliente_vRUC", nullable = false)
	var cliente: Cliente? = null
	@get:Column(name = "nPrecioTotal", precision = 22, scale = 0)
	var nprecioTotal: Double? = null
	@get:Temporal(TemporalType.DATE)
	@get:Column(name = "dFechaCompra", length = 10)
	var dfechaCompra: Date? = null
	@get:Temporal(TemporalType.DATE)
	@get:Column(name = "dFechaPago", length = 10)
	var dfechaPago: Date? = null
	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "ordencompra")
	var facturas: Set<Factura>? = HashSet<Factura>(0)
	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "ordencompra")
	var ordencompraHasProductos: Set<OrdencompraHasProducto>? = HashSet<OrdencompraHasProducto>(0)

	constructor() {}
	constructor(cliente: Cliente?) {
		this.cliente = cliente
	}

	constructor(
		cliente: Cliente?, nprecioTotal: Double?, dfechaCompra: Date?, dfechaPago: Date?, facturas: Set<Factura>?,
		ordencompraHasProductos: Set<OrdencompraHasProducto>?
	) {
		this.cliente = cliente
		this.nprecioTotal = nprecioTotal
		this.dfechaCompra = dfechaCompra
		this.dfechaPago = dfechaPago
		this.facturas = facturas
		this.ordencompraHasProductos = ordencompraHasProductos
	}
}