package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import java.util.HashSet
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType.IDENTITY
import javax.persistence.Id
import javax.persistence.OneToMany
import javax.persistence.Table

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "sdtienda")
class Producto : java.io.Serializable {
	@get:Id
	@get:GeneratedValue(strategy = IDENTITY)
	@get:Column(name = "vCodigo", unique = true, nullable = false)
	var vcodigo: Int? = null
	@get:Column(name = "vNombre", length = 40)
	var vnombre: String? = null
	@get:Column(name = "vDescripcion", length = 40)
	var vdescripcion: String? = null
	@get:Column(name = "nPrecioUnitario", precision = 22, scale = 0)
	var nprecioUnitario: Double? = null
	@get:Column(name = "nCantidad")
	var ncantidad: Int? = null
	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	var ordencompraHasProductos: Set<OrdencompraHasProducto>? = HashSet<OrdencompraHasProducto>(0)

	constructor() {}
	constructor(
		vnombre: String?, vdescripcion: String?, nprecioUnitario: Double?, ncantidad: Int?,
		ordencompraHasProductos: Set<OrdencompraHasProducto>?
	) {
		this.vnombre = vnombre
		this.vdescripcion = vdescripcion
		this.nprecioUnitario = nprecioUnitario
		this.ncantidad = ncantidad
		this.ordencompraHasProductos = ordencompraHasProductos
	}
}