package com.fisi.inventario.entity

// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.EntityListeners
import javax.persistence.FetchType
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.NamedQuery
import javax.persistence.Table
import org.springframework.data.jpa.domain.support.AuditingEntityListener

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "sdtienda")
class Usuario : java.io.Serializable {
	@get:Id
	@get:Column(name = "vIdUsuario", unique = true, nullable = false, length = 20)
	var vidUsuario: String? = null
	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "cliente_vRUC", nullable = false)
	var cliente: Cliente? = null
	@get:Column(name = "vClave", length = 70)
	var vclave: String? = null

	constructor() {}
	constructor(vidUsuario: String?, cliente: Cliente?) {
		this.vidUsuario = vidUsuario
		this.cliente = cliente
	}

	constructor(vidUsuario: String?, cliente: Cliente?, vclave: String?) {
		this.vidUsuario = vidUsuario
		this.cliente = cliente
		this.vclave = vclave
	}

	companion object {
		private val serialVersionUID = 1L
	}
}